### ISSUE TITLE
Auto-delete old frames/audio

### ISSUE THREAD

**Issue by spellboundtriangle** [RinLovesYou/Flipnote-Encoder#8]
Fairly straightforward, it's just a bit of a hassle to have to delete the old frames/audio every time, especially when I'm experimenting with dithering/contrast. Doing so also sends them to the recycle bin, and the chances are I'm not going to care to recover them.

If this could be implemented as an option, like
`"DeleteOldData": 0,`
`0 = never delete old data
1 = always delete old data after success
2 = prompt to delete old data after success
3 = prompt to delete old data if input or options changed`

Maybe 3 could be dropped,  but at least 0 and 1 would be great.
Also, sorry if this is incorrectly formatted, I'm new to GitHub.

Thank you for taking the time to read!

**Comment by RinLovesYou** [comment]
I'll implement that in the performance patch coming sometime tomorrow

**Comment by RinLovesYou** [comment]
Work on PPMLib has delayed this a bit but it should be ready by tomorrow

**Comment by RinLovesYou** [comment]
fixed in [latest](https://github.com/RinLovesYou/Flipnote-Encoder/releases/latest)
